import {
  Activity,
  CircleQuestionMark,
  Ellipsis,
  Eye,
  FileText,
  Filter,
  Home,
  Mail,
  Map,
  MessageCircle,
  Package,
  Phone,
  Search,
  Send,
  Settings,
  Shield,
  UserRoundCheck,
  Users,
  Box,
  DollarSign,
  Clock,
  Truck,
  Bell,
  AlertTriangle,
  CheckCircle,
  Plus,
  CreditCard,
  ShieldCheck,
  Headphones,
  Star,
  MoveLeft,
} from "lucide-react";

const TechIcon = ({ name, className = "" }) => {
  const icons = {
    home: <Home className={className} />,
    send: <Send className={className} />,
    roundcheck: <UserRoundCheck className={className} />,
    elipsis: <Ellipsis className={className} />,
    eye: <Eye className={className} />,
    filter: <Filter className={className} />,
    map: <Map className={className} />,
    file: <FileText className={className} />,
    dollar: <DollarSign className={className} />,
    settings: <Settings className={className} />,
    activity: <Activity className={className} />,
    search: <Search className={className} />,
    question: <CircleQuestionMark className={className} />,
    message: <MessageCircle className={className} />,
    mail: <Mail className={className} />,
    phone: <Phone className={className} />,
    shield: <Shield className={className} />,
    users: <Users className={className} />,
    package: <Package className={className} />,
    box: <Box className={className} />,
    "dollar-sign": <DollarSign className={className} />,
    clock: <Clock className={className} />,
    truck: <Truck className={className} />,
    bell: <Bell className={className} />,
    "alert-triangle": <AlertTriangle className={className} />,
    "check-circle": <CheckCircle className={className} />,
    plus: <Plus className={className} />,
    "credit-card": <CreditCard className={className} />,
    "shield-check": <ShieldCheck className={className} />,
    headphones: <Headphones className={className} />,
    star: <Star className={className} />,
    "move-left": <MoveLeft className={className} />,
  };

  return icons[name.toLowerCase()] || <span className={className}>{name}</span>;
};

export default TechIcon;
